title: "Frontier Tavern – Community Forums"
collections:
  general_posts:
    output: true
    permalink: /general/:slug/
  newst:
    output: true
    permalink: /news/:slug/
  hidden_posts:
    output: true
    permalink: /hidden/:slug/   # URLs like /hidden/secret-note/

defaults:
  - scope:
      path: ""
      type: "general_posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "news"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "hidden_posts"
    values:
      layout: "post" 